########### local ###########
GET http://localhost:9320/api/hello

GET http://localhost:9320/api/simple

########### private cluster ###########
GET http://dev.simple-api.127.0.0.1.sslip.io/api/simple


GET http://dev.simple-api.127.0.0.1.sslip.io:9701/api/simple



########### ncp cluster ###########
GET http://localhost:9320/api/hello
Host: "test.osckorea.com"
