apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: dev
    build:
      local:
        push: true # false는 로컬 테스트
      artifacts:
        - image: oscka/simple-api # on dev server
        # - image: simple-api   # local
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: eclipse-temurin:17.0.2_8-jre
    deploy:
      kubectl:
        manifests:
#      - k8s/dev/ingress.yaml
          - k8s/dev/simple-api-*.yaml 
          - k8s/dev/configmap.yaml 
    # portForward:
    # - resourceType: Service
    #   resourceName: simple-api-service
    #   namespace: api
    #   port: 80
    #   localPort: 8082 # *Optional*
